---
- name: restart sshd service if httpd is running
  hosts: ansible1
  tasks:
  - name: get httpd status
    command: systemctl is-active httpd
    ignore_errors: yes
    register: result
  - name: show result variable
    debug:
      msg: printing contents of the registered variable {{ result }}
  - name: restart sshd service
    service:
      name: sshd
      state: restarted
    when: result.rc == 1
