- name: manage packages using a loop from a list
  become: yes
  hosts: ansible1
  vars_files: vars/packages
  tasks: 
  - name: install packages
    yum: 
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop: "{{ packages }}"
