---
- name: conditionals test
  hosts: all
  tasks: 
  - name: update the kernel if sifficient space is available in /boot
    package: 
      name: kernel
      state: latest
    loop: "{{ ansible_facts['mounts'] }}"
    when: item.mount == '/boot' and item.size_available > 200000000 
