---
- name: conditional test
  hosts: all
  tasks: 
  - name: install vsftpd if sufficient memory available
    package:
      name: vsftpd
      state: latest
    when: ansible_facts['memory_mb']['real']['free'] > 5000
    
