---
- name: get vg sizes
  hosts: all
  tasks:
  - name: find small vgroup sizes
    debug:
      msg: volume group smaller than or equal to 20G
    when:
    - ansible_facts['lvm']['vgs']['c1'] is defind
    - ansible_facts['lvm']['vgs']['c1']['size_g'] <= 20.00
  - name: find large vgroup size
    debug:
      msg: volume group larger than or equal to 19G
    when:
    - ansible_facts['lvm']['vgs']['c1'] is defind
    - ansible_facts['lvm']['vgs']['c1']['size_g'] >= 19.00
