---
- name: install and enable apache web server
  hosts: all
  serial: 2
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: latest
  - name: Start and enable the httpd service
    service: 
      name: httpd
      state: started
      enabled: yes

