---
- hosts: ansible1
  vars:
    timesync_ntp_servers:
      - hostname: pool.ntp.org
        iburst: yes
    timezone: UTC
  roles:
    - rhel-system-roles.timesync
  tasks:
  - name: set timezone
    timezone:
      name: "{{ timezone }}"
