---
- name: set default boot target and reboot
  hosts: ansible2
  tasks:
  - name: set default boot target
    file:
      src: /usr/lib/systemd/system/multi-user.target
      dest: /etc/systemd/system/default.target
      state: link
  - name:
    reboot:
      msg: reboot initiated by ansible
      test_command: whoami
  - name: print message to show that the host is back online
    debug:
      msg: successfully rebooted
   

