---
- name: isntall, configure , start and enable ftp
  hosts: localhost
  tasks: 
  - name: install ftp server
    yum:
      name: vsftpd
      state: latest
  - name: allow anonymous access to ftp
    lineinfile:
      path: /etc/vsftpd/vsftpd.conf
      regexp: '^anonymous_enable=NO'
      line: anonymous_enable=YES
  - name: start ftp server
    service:
      name: vsftpd
      state: started
      enabled: yes
  - name: open firewall for ftp
    firewalld:
      service: ftp
      state: enabled
      immediate: yes
      permanent: yes

- name: setup the repo directory
  hosts: localhost
  tasks: 
  - name: Make a directory
    file:
      path: /var/ftp/repo
      state: directory
  - name: download packages
    yum:
      name: nmap
      download_only: yes
      download_dir: /var/ftp/repo

  - name: install create repo repo
    yum:
      name: createrepo_c
      state: latest
  - name: create repo
    command: createrepo /var/ftp/repo
    notify:
    - restart_ftp
  handlers:
  - name: restart_ftp
    service:
      name: vsftpd
      state: restarted
