---
- name: stat module tests
  hosts: ansible1 
  tasks:
  - command: touch /tmp/statfile
  - stat:
      path: /tmp/statfile
    register: st
  - name: show current values
    debug:
      msg: current value of st variable is {{ st }}
  - name:
    file:
      path: /tmp/statfile
      mode: 0640
    when: st.stat.mode != '0640'
