---
- name: copy facts to managed servers
  hosts: all
  become: yes
  vars:
    remote_dir: "/etc/ansible/facts.d"
    fact_file: "lab6.fact"
  tasks:
  - name: create facts.d folder on managed systems
    file:
      path: "{{ remote_dir }}"
      state: directory
      recurse: yes
  - name: Copy the fact files to the facts.d folder
    copy:
      src: "{{ fact_file }}"
      dest: "{{ remote_dir }}"

