---
- name: test webserver access
  hosts: localhost
  become: no
  tasks:
  - name: connect to the webserver
    uri:
      url: http://ansible2
      return_content: yes
    register: this
    failed_when: "'welcome' not in this.content"
  - debug: 
      var: this.content
