---
- name: enable web server
  hosts: ansible1
  tasks: 
  - name: install stuff
    yum:
      name:
        - httpd
  - name: create a welcome page
    copy:
      content: "Welcome to the webserver\n"
      dest: /var/www/html/index.html
  - name: enable wevserver
    service:
      name: httpd
      state: started
      enabled: yes
  - name: enable firewall
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

- name: test webserver access
  hosts: localhost
  become: no
  tasks: 
  - name: test webserver access  
    uri:
      url: http://ansible1
      return_content: yes
      status_code: 200

